version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    container_name: crud-hacienda-mongo
    ports:
      - "27017:27017"
    volumes:
      - C:\Users\USER\Documents\admin-haciendas\data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: name-mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
